name: Terraform CI (Self-Hosted Terraform)

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: ["main", "dev", "staging"]

jobs:
  fmt:
    name: Test - Terraform Format Check
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.13.4
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

  lint:
    name: Test -Terraform Lint
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.13.4
    steps:
      - uses: actions/checkout@v4

      - name: Install TFLint
        run: |
          apk add --no-cache curl bash
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: |
          tflint --init --config="$(pwd)/.tflint.hcl"
          tflint --recursive --config="$(pwd)/.tflint.hcl"

  plan:
    name: Test - Terraform Plan
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.13.4
    env:
      AWS_REGION: ""
      AWS_ACCOUNT_ID: ""
      AWS_ROLE_NAME: ""
      # if branch == main → prod, otherwise use branch name
      ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false -reconfigure

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Workspace (create or select)
        run: |
          terraform workspace select ${{ env.ENVIRONMENT }} || terraform workspace new ${{ env.ENVIRONMENT }}

      - name: Terraform Apply Plan
        run: |
          terraform plan \
            -input=false \
            -var-file="vars/${{ env.ENVIRONMENT }}.tfvars" \
            -out=tfplan-apply

      - name: Upload Apply Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-apply-${{ env.ENVIRONMENT }}
          path: tfplan-apply


  checkov:
    name: Test - Security Scan
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.13.4
    steps:
      - uses: actions/checkout@v4
      - name: Install Checkov
        run: |
          apk add --no-cache python3 py3-pip
          pip install --break-system-packages checkov

      - name: Run Checkov Scan
        run: |
          checkov -d . --framework terraform --compact --quiet \
          --output-file-path checkov_report.json

      - name: Upload Checkov Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: check/checkov_report.json
          if-no-files-found: ignore

 
  apply:
    name: Deploy - Terraform Apply
    needs: [fmt, lint, plan, checkov]
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.13.4
    env:
      AWS_REGION: ""
      AWS_ACCOUNT_ID: ""
      AWS_ROLE_NAME: ""
      # if branch == main → prod, otherwise use branch name
      ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
      
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js (for GitHub Actions runtime)
        run: |
          apk add --no-cache nodejs npm
          node --version
          npm --version

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download Apply Plan File
        uses: actions/download-artifact@v4
        with:
          name: tfplan-apply-${{ env.ENVIRONMENT }}
          path: ./

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Terraform Init
        run: |
          terraform init -input=false -reconfigure

      - name: Plan review
        if: ${{ github.run_attempt < 2 && env.ENVIRONMENT == 'prod' }}
        run: |
          echo "❌ Failed: please review the plan before applying."
          echo "after reviewing you can run this job again, it will work. (based on 'github.run_attempt' value)"
          echo "make sure to run only the 'apply' job again and not the 'plan' job."
          echo "this check is enabled only in main/prod branch."

          echo "========= PLAN REVIEW ========="
          terraform show tfplan-apply || echo "Plan is binary or missing"
          echo "================================"

          echo "❌ Failed: please review the plan before applying."
          echo "after reviewing you can run this job again, it will work. (based on 'github.run_attempt' value)"
          echo "make sure to run only the 'apply' job again and not the 'plan' job."
          echo "this check is enabled only in main/prod branch."

          exit 1

      - name: Terraform Workspace (create or select)
        run: |
          terraform workspace select ${{ env.ENVIRONMENT }} || terraform workspace new ${{ env.ENVIRONMENT }}

      - name: Terraform Apply
        run: terraform apply -auto-approve "tfplan-apply"
