name: Simple Echo (Self-Hosted)

on:
  push:
    branches:
      - dev

jobs:
  say-hello:
    runs-on: self-hosted
    steps:
      - name: Echo message
        run: echo "Hello from my self-hosted runner!2"
