name: Simple Echo (Self-Hosted)

on:
  push:
    branches:
      - cicd

jobs:
  say-hello:
    runs-on: self-hosted
    container:
      image: alpine:latest
    steps:
      - name: Echo message
        run: echo "Hello from my self-hosted runner!2"
